CREATE DATABASE IF NOT EXISTS mghs_application_portal;

CREATE TABLE IF NOT EXISTS application_portal (
	id INT AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	status VARCHAR(128) NOT NULL,
	email VARCHAR(256) NOT NULL,
	contact_no VARCHAR(256) NOT NULL,
	school VARCHAR(256) NOT NULL,
	branch VARCHAR(256) NOT NULL,
	course VARCHAR(256) NOT NULL,
	skills VARCHAR(256) NOT NULL,
	field_of_work VARCHAR(256) NOT NULL,
	resume VARCHAR(256) DEFAULT "No resume",
	meeting_sched TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS application_portal_admin (
	id INT AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	email VARCHAR(256) NOT NULL,
	username VARCHAR(128) NOT NULL,
	password VARCHAR(256) NOT NULL,
	role VARCHAR(256) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
) ENGINE = INNODB;